=== A4850-G08/XML-SchemaLab9/data/timetable.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema	version="1.0"
			xmlns:xs="http://www.w3.org/2001/XMLSchema"
			elementFormDefault="qualified">
	
	<!--***********************************************************
	*************************XML Data Structure *******************
	************************************************************-->
	<!-- timetable element can have days, timeslots, and courses inside-->
	<xs:element name="timetable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="days" minOccurs="0"/>
				<xs:element name="timeslots" minOccurs="0"/>
				<xs:element name="courses" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- days element will have day elements inside-->
	<xs:element name="days">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="day" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- each day element will take in bookings-->
	<xs:element name="day">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="booking" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="weekday" type="xs:weekdayT" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<!-- booking will have timeslot, courseCode, courseType, room, and instructor-->
	<xs:element name="booking">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="timeslot" type="timeslotT" maxOccurs="1"/>
				<xs:element name="courseCode" type="courseCodeT" maxOccurs="1"/>
				<xs:element name="courseType" type="courseTypeT" maxOccurs="1"/>
				<xs:element name="room" type="roomT" maxOccurs="1"/>
				<xs:element name="instructor" type="personType" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!--***********************************************************
	*******************Data Types needed for validation************
	************************************************************-->
	
	<!-- weekdays have to be one of five-->
	<xs:simpleType name="weekdayT">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Monday"/>
			<xs:enumeration value="Tuesday"/>
			<xs:enumeration value="Wednesday"/>
			<xs:enumeration value="Thursday"/>
			<xs:enumeration value="Friday"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- time is 4 digit time-->
	<xs:simpleType name="timeT">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-2][0-9][0-5][0-9]" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="timeslotT">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="start" type="xs:timeT"/>
				<xs:attribute name="end" type="xs:timeT"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- person type is a string>-->
	<xs:complexType name="personType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="firstName" type="xs:string"/>
				<xs:attribute name="lastName" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<!-- courseType have to be one of two-->
	<xs:simpleType name="courseTypeT">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Lab"/>
			<xs:enumeration value="Lec"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- courseCode is a 4 digit number-->
	<xs:simpleType name="courseCodeT">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-9][0-9][0-9][0-9]" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- weekdays have to be one of five-->
	<xs:simpleType name="roomT">
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Z]{2})\d{1,2}\s\d{3,4}" /> 
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== A4850-G08/XML-SchemaLab9/data/timetable.xml
<?xml version="1.0" encoding="UTF-8"?>

<timetable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="timetable.xsd">
	<!-- 3 different faucets-->
	<days>
		<day weekday="Monday">
			<booking>
				<timeslot start="10:30" end="12:20"></timeslot>
				<courseCode>4650</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
			<booking>
				<timeslot start="15:30" end="16:20"></timeslot>
				<courseCode>4910</courseCode>
				<courseType>Lec</courseType>
				<room>SW1-2005</room>
				<instructor>Richard Chau</instructor>
			</booking>
			<booking>
				<timeslot start="16:30" end="17:20"></timeslot>
				<courseCode>4650</courseCode>
				<courseType>Lec</courseType>
				<room>SE6-205</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
		</day>
		<day weekday="Tuesday">
			<booking>
				<timeslot start="08:30" end="10:20"></timeslot>
				<courseCode>4620</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Bethany Edmunds</instructor>
			</booking>
			<booking>
				<timeslot start="12:30" end="13:20"></timeslot>
				<courseCode>4650</courseCode>
				<courseType>Lec</courseType>
				<room>SE6-205</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
			<booking>
				<timeslot start="15:30" end="17:20"></timeslot>
				<courseCode>4620</courseCode>
				<courseType>Lec</courseType>
				<room>SW1-2020</room>
				<instructor>Bethany Edmunds</instructor>
			</booking>
		</day>
		<day weekday="Wednesday">
			<booking>
				<timeslot start="12:30" end="14:20"></timeslot>
				<courseCode>4850</courseCode>
				<courseType>Lec</courseType>
				<room>SE6-207</room>
				<instructor>James Parry</instructor>
			</booking>
		</day>
		<day weekday="Thursday">
			<booking>
				<timeslot start="09:30" end="10:20"></timeslot>
				<courseCode>4910</courseCode>
				<courseType>Lec</courseType>
				<room>SW1-1205</room>
				<instructor>Richard Chau</instructor>
			</booking>
			<booking>
				<timeslot start="10:30" end="12:20"></timeslot>
				<courseCode>4910</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Richard Chau</instructor>
			</booking>
			<booking>
				<timeslot start="13:30" end="15:20"></timeslot>
				<courseCode>4850</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-308</room>
				<instructor>James Parry</instructor>
			</booking>
		</day>
		<day weekday="Friday">
			<booking>
				<timeslot start="08:30" end="10:20"></timeslot>
				<courseCode>4660</courseCode>
				<courseType>Lec</courseType>
				<room>SW9-206</room>
				<instructor>Steve Fabiszewski</instructor>
			</booking>
			<booking>
				<timeslot start="10:30" end="12:20"></timeslot>
				<courseCode>4770</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Trevor Lord</instructor>
			</booking>
			<booking>
				<timeslot start="13:30" end="15:30"></timeslot>
				<courseCode>4660</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Steve Fabiszewski</instructor>
			</booking>
		</day>
	</days>
	
	<timeslots>
		<timeslot start="08:30" end="10:20">
			<booking>
				<day weekday="Tuesday"></day>
				<courseCode>4620</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Bethany Edmunds</instructor>
			</booking>
			<booking>
				<day weekday="Friday"></day>
				<courseCode>4660</courseCode>
				<courseType>Lec</courseType>
				<room>SW9-206</room>
				<instructor>Steve Fabiszewski</instructor>
			</booking>
		</timeslot>
		<timeslot start="09:30" end="10:20">
			<booking>
				<day weekday="Thursday"></day>
				<courseCode>4910</courseCode>
				<courseType>Lec</courseType>
				<room>SW1-1205</room>
				<instructor>Richard Chau</instructor>
			</booking>
		</timeslot>
		<timeslot start="10:30" end="12:20">
			<booking>
				<day weekday="Monday"></day>
				<courseCode>4650</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
			<booking>
				<day weekday="Tuesday"></day>
				<courseCode>4910</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Richard Chau</instructor>
			</booking>
			<booking>
				<day weekday="Friday"></day>
				<courseCode>4770</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Trevor Lord</instructor>
			</booking>
		</timeslot>
		<timeslot start="12:30" end="13:20">
			<booking>
				<day weekday="Tuesday"></day>
				<courseCode>4650</courseCode>
				<courseType>Lec</courseType>
				<room>SE6-205</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
		</timeslot>
		<timeslot start="12:30" end="14:20">
			<booking>
				<day weekday="Wednesday"></day>
				<courseCode>4850</courseCode>
				<courseType>Lec</courseType>
				<room>SE6-207</room>
				<instructor>James Parry</instructor>
			</booking>
		</timeslot>
		<timeslot start="13:30" end="15:20">
			<booking>
				<day weekday="Thursday"></day>
				<courseCode>4850</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-308</room>
				<instructor>James Parry</instructor>
			</booking>
			<booking>
				<day weekday="Friday"></day>
				<courseCode>4660</courseCode>
				<courseType>Lab</courseType>
				<room>SE12-206</room>
				<instructor>Steve Fabiszewski</instructor>
			</booking>
		</timeslot>
		<timeslot start="15:30" end="16:20">
			<booking>
				<day weekday="Monday"></day>
				<courseCode>4910</courseCode>
				<courseType>Lec</courseType>
				<room>SW1-2005</room>
				<instructor>Richard Chau</instructor>
			</booking>
		</timeslot>
		<timeslot start="16:30" end="17:20">
			<booking>
				<day weekday="Monday"></day>
				<courseCode>4650</courseCode>
				<courseType>Lec</courseType>
				<room>SE6-205</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
		</timeslot>
		<timeslot start="15:30" end="17:20">
			<booking>
				<day weekday="Tuesday"></day>
				<courseCode>4620</courseCode>
				<courseType>Lec</courseType>
				<room>SW1-2020</room>
				<instructor>Bethany Edmunds</instructor>
			</booking>
		</timeslot>
	</timeslots>
	
	<courses>
		<course courseCode="4910">
			<booking>
				<day weekday="Monday"></day>
				<timeslot start="15:30" end="16:20"></timeslot>
				<courseType>Lec</courseType>
				<room>SW1-2005</room>
				<instructor>Richard Chau</instructor>
			</booking>
			<booking>
				<day weekday="Thursday"></day>
				<timeslot start="09:30" end="10:20"></timeslot>
				<courseType>Lec</courseType>
				<room>SW5-1840</room>
				<instructor>Richard Chau</instructor>
			</booking>
			<booking>
				<day weekday="Thursday"></day>
				<timeslot start="15:30" end="16:20"></timeslot>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Richard Chau</instructor>
			</booking>
		</course>
		<course courseCode="4660">
			<booking>
				<day weekday="Friday"></day>
				<timeslot start="08:30" end="10:20"></timeslot>
				<courseType>Lec</courseType>
				<room>SW9-206</room>
				<instructor>Steve Fabiszewski</instructor>
			</booking>
			<booking>
				<day weekday="Friday"></day>
				<timeslot start="13:30" end="15:20"></timeslot>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Steve Fabiszewski</instructor>
			</booking>
		</course>
		<course courseCode="4770">
			<booking>
				<day weekday="Friday"></day>
				<timeslot start="10:30" end="12:20"></timeslot>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Trevor Lord</instructor>
			</booking>
		</course>
		<course courseCode="4650">
			<booking>
				<day weekday="Monday"></day>
				<timeslot start="10:30" end="12:20"></timeslot>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
			<booking>
				<day weekday="Monday"></day>
				<timeslot start="16:30" end="17:20"></timeslot>
				<courseType>Lec</courseType>
				<room>SE6-205</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
			<booking>
				<day weekday="Tuesday"></day>
				<timeslot start="12:30" end="13:20"></timeslot>
				<courseType>Lec</courseType>
				<room>SE6-205</room>
				<instructor>Medhat Elmasry</instructor>
			</booking>
		</course>
		<course courseCode="4620">
			<booking>
				<day weekday="Tuesday"></day>
				<timeslot start="08:30" end="10:20"></timeslot>
				<courseType>Lab</courseType>
				<room>SE12-306</room>
				<instructor>Bethany Edmunds</instructor>
			</booking>
			<booking>
				<day weekday="Tuesday"></day>
				<timeslot start="15:30" end="17:20"></timeslot>
				<courseType>Lec</courseType>
				<room>SW1-2020</room>
				<instructor>Bethany Edmunds</instructor>
			</booking>
		</course>
		<course courseCode="4850">
			<booking>
				<day weekday="Wednesday"></day>
				<timeslot start="12:30" end="14:20"></timeslot>
				<courseType>Lec</courseType>
				<room>SE6-207</room>
				<instructor>James Parry</instructor>
			</booking>
			<booking>
				<day weekday="Thursday"></day>
				<timeslot start="13:30" end="15:20"></timeslot>
				<courseType>Lab</courseType>
				<room>SE12-308</room>
				<instructor>James Parry</instructor>
			</booking>
		</course>
	</courses>
</timetable>
